#宋国
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(2, 1, '布料类服装');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(2, 2, '皮甲类服装');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(2, 3, '铠甲类服装');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(2, 4, '刀盾类');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(2, 5, '弓类');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(2, 6, '棍类');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(2, 7, '杖类');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(2, 8, '扇类');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(2, 9, '项链类');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(2, 10, '戒指类');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(2, 11, '护腕类');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(2, 12, '腰带类');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(2, 13, '鞋子类');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(2, 14, '头盔类');

#魏国
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(3, 1, '布料类服装');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(3, 2, '皮甲类服装');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(3, 3, '铠甲类服装');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(3, 4, '刀盾类');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(3, 5, '弓类');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(3, 6, '棍类');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(3, 7, '杖类');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(3, 8, '扇类');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(3, 9, '项链类');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(3, 10, '戒指类');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(3, 11, '护腕类');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(3, 12, '腰带类');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(3, 13, '鞋子类');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(3, 14, '头盔类');

#齐国
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(4, 1, '布料类服装');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(4, 2, '皮甲类服装');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(4, 3, '铠甲类服装');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(4, 4, '刀盾类');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(4, 5, '弓类');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(4, 6, '棍类');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(4, 7, '杖类');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(4, 8, '扇类');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(4, 9, '项链类');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(4, 10, '戒指类');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(4, 11, '护腕类');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(4, 12, '腰带类');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(4, 13, '鞋子类');
INSERT INTO `TECH` (COUNTRYID, TYPE, NAME) VALUES(4, 14, '头盔类');

