-- 升级 REG_EMAIL_CODE 与回调字段、抽奖功能表
ALTER TABLE REG_EMAIL_CODE
ADD COLUMN scene VARCHAR(32) NOT NULL DEFAULT 'default',
ADD COLUMN is_fail TINYINT(1) NOT NULL DEFAULT 0;

ALTER TABLE RECHARGEORDERS
ADD COLUMN PAID_AT DATETIME DEFAULT NULL,
ADD COLUMN TRADE_NO VARCHAR(64) DEFAULT NULL;

CREATE TABLE IF NOT EXISTS LOTTERY_POOL (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(64) NOT NULL,
  REWARD_POINTS INT NOT NULL DEFAULT 0,
  WEIGHT INT NOT NULL DEFAULT 0,
  IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS LOTTERY_LOG (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  UID INT NOT NULL,
  ACCOUNT VARCHAR(48) NOT NULL,
  PRIZE_ID INT NOT NULL,
  PRIZE_NAME VARCHAR(64) NOT NULL,
  CHANGE_POINTS INT NOT NULL DEFAULT 0,
  COST_POINTS INT NOT NULL DEFAULT 0,
  CLIENT_SEED VARCHAR(64) NOT NULL,
  SERVER_SEED_HASH VARCHAR(64) NOT NULL,
  NONCE INT NOT NULL,
  RESULT_HASH VARCHAR(64) NOT NULL,
  CREATED_AT DATETIME NOT NULL,
  KEY idx_created_at (CREATED_AT)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
